### ISSUE TITLE
Stackage?

### ISSUE THREAD

**Issue by joehillen** [aurapm/haskell-versions#2]
Any interest in adding this package to Stackage?

https://github.com/fpco/stackage#add-your-package

**Comment by fosskers** [comment]
Thanks, I'm surprised that I haven't already. Let me fix few things up and I'll fire it up.

**Comment by fosskers** [comment]
1.1.0 uploaded to Hackage.

**Comment by fosskers** [comment]
https://github.com/fpco/stackage/pull/1387

**Comment by fosskers** [comment]
It's merged into stackage, so hopefully it will be in tomorrow's nightly.
